# Generated by Django 4.2.13 on 2024-06-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_created_at_contact_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
    ]
