# Generated by Django 4.2.13 on 2026-09-01 22:14

from django.db import migrations, models
import django.db.models.deletion


def map_legacy_statuses(apps, schema_editor):
    lead_model = apps.get_model('water_calculator', 'CustomerSurveyLead')
    lead_model.objects.filter(status='qualified').update(status='contacted')
    lead_model.objects.filter(status='closed').update(status='lost')


class Migration(migrations.Migration):

    dependencies = [
        ('water_survey', '0002_rainfall_grid'),
        ('water_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurveylead',
            name='gross_rainfall_litres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customersurveylead',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customersurveylead',
            name='location_method',
            field=models.CharField(choices=[('map', 'Mapped roof location'), ('postcode', 'Approximate postcode centre')], default='map', max_length=12),
        ),
        migrations.AddField(
            model_name='customersurveylead',
            name='monthly_estimate',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customersurveylead',
            name='rainfall_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='customersurveylead',
            name='runoff_coefficient',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='customersurveylead',
            name='survey',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculator_lead', to='water_survey.survey'),
        ),
        migrations.AddField(
            model_name='customersurveylead',
            name='survey_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersurveylead',
            name='system_efficiency',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='customersurveylead',
            name='uncaptured_litres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RunPython(map_legacy_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customersurveylead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('survey_requested', 'Survey Requested'), ('contacted', 'Contacted'), ('survey_booked', 'Survey Booked'), ('surveyed', 'Surveyed'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
